---
- hosts: all

  sudo: yes

  tasks:

    ###

    # Bootstrap repositories installed with RPMs.  Based on an "a-ha!"
    # moment from <http://stackoverflow.com/a/14155303/722332>.

    - name: bootstrap asterisknow-version install
      copy: src=ansible-bootstrap-asterisk-current.repo
            dest=/etc/yum.repos.d/
            owner=root group=root mode=0644

    - name: asterisknow-version install
      yum: name=asterisknow-version
           enablerepo=ansible-bootstrap-asterisk-current
           state=present

    ###

    - name: asterisk-11 repository enable
      ini_file: dest=/etc/yum.repos.d/centos-asterisk-11.repo
                section=asterisk-11
                option=enabled
                value=1

    - name: asterisk installation
      yum: name=asterisk state=present

    ###

    # In Ansible 1.4, this will work first try.

    - name: link asterisk config directory 
      file: src=/vagrant/etc/asterisk dest=/etc/asterisk state=link force=yes
      register: link_asterisk_config
      ignore_errors: yes
      notify: restart asterisk

    # In Ansible 1.3, this is needed to catch failure of the above, as
    # directories cannot be forced to links.

    - name: remove asterisk config directory
      file: name=/etc/asterisk state=absent
      when: link_asterisk_config|failed

    - name: link asterisk config directory again
      file: src=/vagrant/etc/asterisk dest=/etc/asterisk state=link
      when: link_asterisk_config|failed
      notify: restart asterisk

    ###

    - name: enable asterisk
      service: name=asterisk enabled=yes

    - name: bootstrap epel-release install
      copy: src=ansible-bootstrap-epel.repo
            dest=/etc/yum.repos.d/
            owner=root group=root mode=0644

    - name: epel-release install
      yum: name=epel-release
           enablerepo=ansible-bootstrap-epel
           state=present

    - name: epel repository restrict
      ini_file: dest=/etc/yum.repos.d/epel.repo
                section=epel
                option=includepkgs
                value='python-virtualenv python-pip'

    - name: epel repository enable
      ini_file: dest=/etc/yum.repos.d/epel.repo
                section=epel
                option=enabled
                value=1

    - name: python virtualenv/pip installation
      yum: pkg={{ item }} state=present
      with_items:
        - python-virtualenv
        - python-pip

  handlers:

    - name: restart asterisk
      service: name=asterisk state=restarted

